services:

  etcd:
    image:  quay.io/coreos/etcd:v3.5.13
    environment:
      - ETCD_NAME=etcd0
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2382
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2383
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2383
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2382
    ports:
      - "2383:2383"
      - "2382:2382"

  patroni1:
    image: registry.opensource.zalan.do/acid/spilo-14:2.1-p5
    environment:
      PATRONI_NAME: node1
      PATRONI_SCOPE: pg-cluster
      PATRONI_ETCD_HOSTS: etcd:2383
      PATRONI_REST_API_LISTEN: 0.0.0.0:8008
      PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5432
      PATRONI_POSTGRESQL_DATA_DIR: /home/postgres/data
      PGPASSWORD_SUPERUSER: postgres
      PGPASSWORD_ADMIN: postgres
      PATRONI_POSTGRESQL_PARAMETERS=wal_level: logical
      PATRONI_POSTGRESQL_HBA: 'host all all 0.0.0.0/0 md5'
    ports:
      - "5433:5432"
      - "8008:8008"
    volumes:
      - patroni1-data:/home/postgres/data
    depends_on:
      - etcd

  patroni2:
    image: registry.opensource.zalan.do/acid/spilo-14:2.1-p5
    environment:
      PATRONI_NAME: node2
      PATRONI_SCOPE: pg-cluster
      PATRONI_ETCD_HOSTS: etcd:2383
      PATRONI_REST_API_LISTEN: 0.0.0.0:8008
      PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5432
      PATRONI_POSTGRESQL_DATA_DIR: /home/postgres/data
      PGPASSWORD_SUPERUSER: postgres
      PGPASSWORD_ADMIN: postgres
    ports:
      - "5434:5432"
      - "8009:8008"
    volumes:
      - patroni2-data:/home/postgres/data
    depends_on:
      - etcd

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    volumes:  
     - pgadmin-data:/var/lib/pgadmin  
    depends_on:
      - patroni1
      - patroni2
volumes:
  patroni1-data:
  patroni2-data:
  pgadmin-data: