apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXM=  # postgres (base64)
  DB_PASSWORD: cG9zdGdyZXM=  # 123456789 (base64)
  ARGOCD_SERVER: localhost:8080
  ARGOCD_USERNAME: YWRtaW4=
  ARGOCD_PASSWORD: Q3zU8R9-aKy02m2m